id = "{{ project-name }}"
name = "{{ project-name }}"
description = "{{ extension_description }}"
version = "0.0.1"
schema_version = 1
authors = ["{{ extension_author }}"]
repository = "{{ extension_repository }}"

{% if include_grammar %}
[grammars.{{ language_name }}]
repository = "{{ grammar_repository }}"
commit =  "{{ grammar_commit }}"
{% endif %}