id = "{{ project-id }}"
name = "{{ project-name }}"
description = "{{ project-description }}"
version = "0.0.1"
schema_version = 1
authors = ["{{ authors }}"]
repository = "{{ repository-url }}"

# See more information about an "extension.toml" file by following the link below
# https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md#extension-structure
